{% set name = "google-cloud-vision" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c349f771ee49027781e05df2efa6fc1a8b4f7d1d74ab57675f9151a04b01d6f

build:
  # Missing protobuf <4 for py313
  skip: true  # [py<37 or py>312]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - protobuf <4.0.0dev

test:
  downstreams:
    - layoutparser
  source_files:
    - tests
  imports:
    - google.cloud.vision
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - mock

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-vision
  summary: Google Cloud Vision API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    The Python Client for Google Cloud Vision API provides an easy-to-use interface
    to analyze images using advanced machine learning models. It can classify images,
    detect objects, faces, and text, moderate content, and perform sentiment analysis,
    supporting integration with Google Cloud Storage. Compatible with Python 3.7 and above,
    it requires setting up a Google Cloud project, enabling billing,
    and configuring authentication.

  doc_url: https://cloud.google.com/python/docs/reference/vision/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-vision

extra:
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
