{% set name = "google-cloud-vision" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-vision-{{ version }}.tar.gz
  sha256: 7bb1e327f0cdb3133a745afb10238f66c09387d34ddd7de27150c79de4bd5da0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0

test:
  imports:
    - google.cloud.vision
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-vision
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Client for Google Cloud Vision
  description: |
    Python Client for Google Cloud Vision
    -------------------------

    The [Google Cloud Vision](https://cloud.google.com/vision/) API enables developers to
    understand the content of an image by encapsulating powerful machine
    learning models in an easy to use REST API. It quickly classifies images
    into thousands of categories (e.g., "sailboat", "lion", "Eiffel Tower"),
    detects individual objects and faces within images, and finds and reads
    printed words contained within images. You can build metadata on your
    image catalog, moderate offensive content, or enable new marketing
    scenarios through image sentiment analysis. Analyze images uploaded
    in the request or integrate with your image storage on Google Cloud
    Storage.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/vision/)
    - [Product Documentation](https://cloud.google.com/vision/reference/rest/)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.5

    Deprecated Python Versions
    -----------
    Python == 2.7. Python 2.7 support will be removed on January 1, 2020.

  doc_url: https://googleapis.github.io/google-cloud-python/latest/vision/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/vision

extra:
  recipe-maintainers:
    - BrentDorsey
    - parthea
    - xylar
