{% set name = "google-cloud-vision" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-vision-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/c3/fe/32f354e0a356b8972819944ebf226970300121d6468f6a02b4e02e4d262e/google_cloud_vision-3.8.1.tar.gz
  # url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #https://files.pythonhosted.org/packages/61/2a/0088c5cff6932be3868aafc38b1132fa64b4bf9a12743a92547a97390a20/google_cloud_vision-3.9.0.tar.gz
  sha256: 75c7f9c22199ba663cea7d6c1193d5a72ac1e5e2215346a852af133ce69c4f5f

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - google-api-core-grpc >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - proto-plus >=1.22.3,<2.0.0dev  # [py<313]
    - proto-plus >=1.25.0,<2.0.0dev  # [py>=313]
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.vision
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-vision
  summary: Google Cloud Vision API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Python Client for Google Cloud Vision
    -------------------------

    The [Google Cloud Vision](https://cloud.google.com/vision/) API enables developers to
    understand the content of an image by encapsulating powerful machine
    learning models in an easy to use REST API. It quickly classifies images
    into thousands of categories (e.g., "sailboat", "lion", "Eiffel Tower"),
    detects individual objects and faces within images, and finds and reads
    printed words contained within images. You can build metadata on your
    image catalog, moderate offensive content, or enable new marketing
    scenarios through image sentiment analysis. Analyze images uploaded
    in the request or integrate with your image storage on Google Cloud
    Storage.

    - [Client Library Documentation](https://googleapis.dev/python/vision/latest/index.html)
    - [Product Documentation](https://cloud.google.com/vision/reference/rest/)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.7

  doc_url: https://googleapis.dev/python/vision/latest/index.html
  dev_url: https://github.com/googleapis/python-vision

extra:
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
