travis:
  secure:
    BINSTAR_TOKEN: FWv9/JvcdkQTm6pYw3wohlncGrnt0iFdG/I8pVw4j5/9/hlEmjhxZKdXPYykiI3xBr2OI0VSGONT2NF/qV+nDey8u8MpAyo8Ee8Pp9ab3+oK5Xn/fpOc5oSRpfwj8YMbEktMPj379coq6o0gqr/FTUQBcCBazxqyPM5dEks9lavjk0YWSv2v+SeOgLfYaNHewxHy8wYqwd4l1Znap5+igKXrbWcK2k529Yuvb+QDJYSXvQ9SSZLN8TcPvHq6I1lfwc9eXhZBFtgErK4b8t3qaxs6A04K12bv5qSms7kCj1I2CtgVWw5u1x1c4kOirUYfia215ueCbj9WonI/nfqOgRZatpVCjeAr0dyn43iluo1DARuCoL+V39WCTnIzFtG+J7eALqNl9x0H9IkjaAoPiDkMtsZwxBE+PPuFzESi0EM1s+2SASSBDb4gSDy4P2AkdlWZVQJxokPrlY+NJmZDtWA+Bj0BLKRHWp1CyQUKBrppwN0IrqP0i23ALPRjmr6Ox10ZQKtbUxj+N+Y5ROyiPKOqfxPla2HdWWUE5dr/FhrOHIG8ID8uctUDlq8CBQQnBDwQslMKBz3G4F4Fv9LusmIkKJpLe82WwKiQRHqcdoQ0Mu/PHR0kc7zwLlixfq4bYQD1aK50V2WlpyM9w1bLBVqXIowSRIjgM5NbQ68RQpw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
